"""Initial migration

Revision ID: 2b934b20702d
Revises: 
Create Date: 2025-04-07 14:45:55.804399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b934b20702d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barcode_id', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['barcode_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('barcode_id')

    # ### end Alembic commands ###
