"""Increase status column length

Revision ID: 8cd878c7e835
Revises: 952733ba3fbc
Create Date: 2025-04-08 09:30:18.231517

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cd878c7e835'
down_revision = '952733ba3fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('planned', 'in_progress', 'completed', 'failed'),
               type_=sa.String(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('production_order', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('planned', 'in_progress', 'completed', 'failed'),
               nullable=False)

    # ### end Alembic commands ###
